title: likeflames's website
description: 存放一些照片，所感，笔记...
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
author:
  name: "likeflames"
  email: "iamwujianhua@163.com"
url: "https://www.likeflames.top"
